#FLAGS = -Wall -Wextra -Werror -g
FLAGS = -g

programa: ejer1 ejer2 ejer3 ejer4 ejer5

ejer1 : ejer1.c
	gcc $(FLAGS) -o ejer1 ejer1.c

ejer2 : ejer2.c
	gcc $(FLAGS) -o ejer2 ejer2.c

ejer3 : ejer3.c
	gcc $(FLAGS) -o ejer3 ejer3.c

ejer4 : ejer4.c
	gcc $(FLAGS) -o ejer4 ejer4.c

ejer5 : ejer5.c
	gcc $(FLAGS) -o ejer5 ejer5.c

clear :
	rm ejer1 ejer2 ejer3 ejer4 ejer5
